set(CMAKE_C_COMPILER "/opt/llvm-22.1.8/bin/clang" CACHE FILEPATH "")
set(CMAKE_CXX_COMPILER "/opt/llvm-22.1.8/bin/clang++" CACHE FILEPATH "")
set(CMAKE_C_FLAGS_INIT "--gcc-toolchain=/opt/gcc-16.1")
set(CMAKE_CXX_FLAGS_INIT "--gcc-toolchain=/opt/gcc-16.1")
set(CMAKE_EXE_LINKER_FLAGS_INIT "--gcc-toolchain=/opt/gcc-16.1 -fuse-ld=lld")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "--gcc-toolchain=/opt/gcc-16.1 -fuse-ld=lld")
