set(CMAKE_C_COMPILER "/opt/clang-p2996/bin/clang" CACHE FILEPATH "")
set(CMAKE_CXX_COMPILER "/opt/clang-p2996/bin/clang++" CACHE FILEPATH "")
set(CMAKE_CXX_FLAGS_INIT "-stdlib=libc++")
set(CMAKE_EXE_LINKER_FLAGS_INIT "-fuse-ld=lld")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "-fuse-ld=lld")
