find_package(Boost 1.91 CONFIG REQUIRED COMPONENTS process)
find_package(CLI11 CONFIG REQUIRED)
find_package(fmt CONFIG REQUIRED)
find_package(glaze CONFIG REQUIRED)
find_path(PICOSHA2_INCLUDE_DIR NAMES picosha2.h REQUIRED)
add_library(picosha2::picosha2 INTERFACE IMPORTED)
set_property(TARGET picosha2::picosha2 PROPERTY
  INTERFACE_INCLUDE_DIRECTORIES "${PICOSHA2_INCLUDE_DIR}")
find_package(spdlog CONFIG REQUIRED)
find_package(stdexec CONFIG REQUIRED)
find_package(ut CONFIG REQUIRED)
